### ISSUE TITLE
Extra comma when ending sprintf potentially causing site-wide fatal server error

### ISSUE THREAD

**Issue by KZeni** [ThimPressWP/thim-core#4]
The latest version released today/yesterday introduced a bug that causes a site-wide fatal server error on PHP 7.2.

Thankfully this is a quick fix.

`inc/functions.php` currently has (around lines 59-62):
```
$html .= sprintf(
	'<a class="post-image" href="%1$s" title="%2$s"><img src="%3$s" alt="%2$s"></a>',
	esc_url( get_permalink() ), esc_attr( the_title_attribute( 'echo=0' ) ), $image,
);
```
which simply needs to become:
```
$html .= sprintf(
	'<a class="post-image" href="%1$s" title="%2$s"><img src="%3$s" alt="%2$s"></a>',
	esc_url( get_permalink() ), esc_attr( the_title_attribute( 'echo=0' ) ), $image
);
```
to fix the issue.

You can see it's really just a matter of removing the extra comma at the end (after `$image`).

All PHP versions are fine with extra commas being at the end of arrays & things, but there are some PHP versions (ex. 7.2.x) that then have an issue if/when there's an extra comma at the end of a function's parameters.

Hopefully, this is a quick fix where having extra commas at the end of function parameters can be avoided (it's not like the extra comma is doing anything... it's effectively just adding the potential of a parse error & nothing else.) Otherwise, I'd like to see this plugin updated to state it requires something like PHP 7.3+ so that sites that might be running potentially problematic PHP versions simply don't update to newer, unsupported, versions (while they should then really look to update their PHP as this really wouldn't be the only plugin to have PHP requirements like this.)

**Comment by tungnxt89** [comment]
Hi KZeni,

Thanks for that, we updated it.
